command.go
command_test.go
coordinator.go
m_etcd/coordinator.go
metafora.go
slowtask_test.go

Back when we made Run's return value (done bool) in 26274e5 -- that
implicitly made Run the sole arbiter of whether or not to Release a task
or Mark it as done.
The only thing the core Consumer should do is tell handlers to Stop --
it should only ever call Release or Done after Run exits and use that
return value.
We do lose the ReleaseTask command (since now it's the same as the
StopTask command), but we've never used it and it can be added later if
it's found to be valuable.

Fix double task release on shutdown

---

embedded/coordinator.go
embedded/embedded_test.go
metafora.go

This fixes a deadlock in embedded tests where a task is released during shutdown but there's no watcher to accept it.
Related to #94

Don't block Releases on corresponding Watches

---

balancer.go
balancer_res.go
balancer_res_test.go
balancer_test.go
httputil/httputil.go
metafora.go
metafora_test.go
resreporter/mem_linux.go
resreporter/mem_linux_test.go
slowtask_test.go
task.go

Minimum viable fix for *Balancer using system-level stats #44*
Unfortunately this includes a change to the Balancer interface to expose more metadata about tasks. It's not required for this feature, but I think it's generally useful.
* Design ``ResourceBalancer`` as just the logic around a ``ResourceReporter`` (**please come up with a better name for that**). The balancer part just compares the reported resources against configurable thresholds ot make balancing decisions.
* Implement a ``Memory`` resource reporter **for Linux only.** I tried to find a cross platform solution, but my solution doesn't even take into account all the eccentricities of the Linux memory model (Committed and Swap are ignored!). Cross platform will have to be piecemeal unless somebody finds a good third party …

Implement resource balancer

---

balancer.go
balancer_res.go
balancer_res_test.go
balancer_test.go
coordinator.go
examples/koalemosd/main.go
logger.go
m_etcd/client.go
m_etcd/client_test.go
m_etcd/coordinator.go
m_etcd/coordinator_test.go
m_etcd/taskmgr.go
metafora.go
metafora_test.go
resreporter/mem_linux.go
util_test.go

Pros:
* Compatible with *log.Logger or
* Simpler API for Metafora components.
* Smaller context interfaces.
* Contextualized logger was flaky and displayed `<autogenerated>`
instead of the filename due to calldepth being wrong.
* Logger can be reused by apps or set by apps. (Less
opinionated/specialized)
Cons:
* Can't set the logger to a `testing.T` for tests and get parallel
per-test logs. Seems like a small sacrifice.
* Larger global API.

Switch to a global logger instead of contextualized ones

---

examples/koalemosd/handler.go
examples/koalemosd/main.go
logger.go

Also improve the logging in koalemosd as it's the easiest way to peek at what "real" log output is going to look like.
The stack depth was off-by-one in the log output which made every log line appear to be from "logger.go". The reason it was off is because I added the debug/info/warn/error helper methods in PR #106

Fix stack depth in new logger

---

balancer.go
balancer_test.go
coordinator.go
embedded/coordinator.go
embedded/embedded_test.go
httputil/httputil_test.go
ignore.go
ignore_test.go
m_etcd/balancer_test.go
m_etcd/coordinator.go
m_etcd/coordinator_test.go
m_etcd/helpers_test.go
m_etcd/taskmgr.go
m_etcd/taskmgr_test.go
metafora.go
metafora_test.go
slowtask_test.go
util_test.go

**API breaks: Coordinator and Balancer**
This change makes Metafora look uglier in the abstract but actually
handle operational realities better. The existing CanClaim interface
didn't reflect reality: if it rejected a task the Coordinator's Watch
method might just continue returning only that task forever...and in a
tight loop no less! There was no way for the Coordinator's Watch and
Balancer to communicate (unless they implemented shared state outside
the Consumer which sounds really tricky to get right).
This design makes Coordinator.Watch stream claimable tasks back to the
Consumer. The Consumer checks an ignore-list before even calling
Balancer.CanClaim. If a task isn't ignored, CanClaim can cause it to be
ignored until a deadline.
Once the deadline is up *the Consumer handles the …

CanClaim rejects tasks for a period of time.

---

balancer.go
httputil/httputil.go
m_etcd/client.go
m_etcd/commander.go
m_etcd/coordinator.go
m_etcd/integration_test.go
m_etcd/statestore.go
m_etcd/taskmgr.go
metafora.go
statemachine/README.md
statemachine/statemachine.go
statemachine/statemachine_test.go
task.go

Sorry for the mega-PR! I'll try to point out the discrete bits:
* Expose state via http handler for handlers that support it: [`httputil`](https://github.com/lytics/metafora/pull/114/files#diff-1b9c09fd51c2c282d47901bb1b888645)
* Improve coordinator/consumer name logging all over the place
* Fix shutdown/release race in `taskmgr` & `Consumer.Shutdown`
* [Drop invalid commands](https://github.com/lytics/metafora/pull/114/files#diff-490e54f090d107c4b07c3da6958589beR253) - Previously invalid commands would cause the handler to go into an error state. It seemed wrong to put the *handler* in an error state when it was the *sender* of the command that made the mistake.

Statemachine improvements

---

m_etcd/commander.go
m_etcd/coordinator.go
m_etcd/transport.go

Bug in etcd/Go causes an occasional panic: https://github.com/coreos/go-etcd/issues/197
This fix adds a recover around watches, with a short pause and resume.
This is fixed in Go 1.5, and we should remove this hack when it is available; forever retrying on a panic is terrifying.

Handle panics in etcd client on watch

---

balancer.go

This fixes a fun bug where only 1 task exists in a cluster. Each node
will claim it and then try to release it to be fair until no one can
claim it.

When fair balancing, having <= 1 task is always fair

---

balancer.go
m_etcd/coordinator.go
metafora.go

It was observed when restarting a cluster that if a node won the first
claim it would win *all* subsequent claims as claiming and failing to
claim take nearly identical resources.
This slows down the "winner" to try to encourage a fairly balanced
cluster.
While balancers are probably a better place to do this, the consumer
should prevent pathological behaviors like we were seeing, so I think a
slight sleep in the core consumer is fine.

Sleep after successful claims to encourage fairness

---

ignore.go
ignore_test.go

Previously if Consumer.Shutdown was called while the Consumer was adding
an ignored task, the ignore manager's send of the task to the
ignored-task-monitor would block forever -- preventing shutdown of the
consumer.
This change allows the sending of the ignored task to the monitor to
abort if a shutdown has been initiated. Note that this leaves the
ignoremgr's map and timeheap in an inconcistent state during shutdowns,
but there's no case in which they're used during shutdown so it's safe.

Fix race when adding ignore during shutdown

---

balancer.go

The problem:
* `FairBalancer.Balance()` releases tasks and sets the internal delay
* Coordinator tries to claim rebalanced tasks, Claim fails, sets ignore
* This step repeats until `Balance()` is called again
The affects:
* Spams logs (because often only 1 or 2 tasks are released)
* Prevents any new claims after a rebalance which could cause a
misbalanced cluster and more balancing!
The fix:
Set an *absolute* time for the delay instead of a relative time. Once
the delay expires, all tasks can be claimed even if they're the ones
recently released.
This should prevent a node from reclaiming tasks it *just* released, but
it doesn't totally prevent the node from claiming tasks until the next
Balance call.

Fix bad behavior where fair balancer would spin after releasing tasks

---

statemachine/run_test.go
statemachine/statemachine.go

I don't like this code, but that doesn't mean it's not a good idea. It's
just very easy for a handler to accidently orphan a goroutine that
receives commands. That effectively steals commands from e.g. sleep's
select cases.
A better solution might be a totally different API for sending commands
to tasks (perhaps a Command(m Message) method for handlers to implement.

Make stateful handler command chan very defensive

---

embedded/commander.go
embedded/commander_test.go
embedded/embedded_test.go
embedded/task.go
m_etcd/commander.go
m_etcd/coordinator_test.go
m_etcd/integration_test.go
m_etcd/task_test.go
statemachine/commander.go
statemachine/errors.go
statemachine/run_test.go
statemachine/statemachine.go
statemachine/statemachine_test.go
task.go

Just a smattering of little changes to ease integration into our internal system.
No real reason for the switch from a Message value to a Message pointer; just seemed slightly more idiomatic.
I probably should have gone ahead and done #135, but there's more important work to get to.

Pointer, helper functions for Messages, and a Valid method for State

---

Documentation/design.md
README.md

[I made the mistake of telling](https://twitter.com/aphyr/status/629536598498000897) @aphyr about our exactly once claim, so I figure I should probably hurry up and document why it's a lie before becoming a tire fire slide.
I also made #139 because we should really offer users clearer configuration options when it comes to attempting to maintain exactly once semantics.

Define limitations of exactly once guarantee

---

.travis.yml
m_etcd/commander.go
m_etcd/commander_test.go
m_etcd/coordinator_test.go
m_etcd/task_test.go

The etcd command listener was improperly ignoring commands sent before
the listener was created. It also needed some tests!
I also figured out a way to run etcd on Travis and enable our etcd integration tests. Definitely opens us up to more timing-related test failures, but I'd rather fix them then rely on fast local machines narrowly avoiding them.

Fix etcd command listener for existing commands

---

.travis.yml
embedded/embedded_test.go
examples/koalemosd/main.go
m_etcd/balancer.go
m_etcd/balancer_test.go
m_etcd/client.go
m_etcd/conf.go
m_etcd/const.go
m_etcd/coordinator.go
m_etcd/coordinator_test.go
m_etcd/helpers_test.go
m_etcd/integration_test.go
m_etcd/parse_test.go
m_etcd/statestore.go
m_etcd/task_test.go
statemachine/run_test.go
util_test.go

The big functional change in this PR is to bump the TTLs for claims and nodes keys in etcd.
see: https://github.com/lytics/metafora/pull/145/files#diff-3b20c32ce08787bae06461304543c2ce
* I bumped `ClaimTTL` to lessen the load on our etcd cluster.
* I bumped `NodeTTL` to make us more resilient to brief network partitions.
The only downside to higher TTLs is that if a metafora crashes it will be longer before the tasks it had claimed are picked up by others. Given the rarity of this event, 3 minutes seems like a reasonably short period of time.
However the bulk of this PR is switching to a Config struct for the etcd related components. Before the TTLs were globals which made testing difficult and is just an awkward way to treat such important values.
The Config struct makes it a lot more …

Lessen etcd load

---

statemachine/statemachine.go

Like Pause when Paused, it should be a noop

Run event when runnable shouldn't cause an error

---

m_etcd/coordinator.go

In order to use the consistent balancer, we desire a 2ndary way of detecting tasks.

Refresh tasks

---

Documentation/introduction.md

Closes #158 
In addition to fixing the few grammatical issues, this also removes some unneeded trailing whitespace. Let me know if you'd prefer I squash these two commits into one.

#158 Fix grammatical issues in Introduction documentation

---

examples/koalemosd/main.go
metcdv3/balancer.go
metcdv3/balancer_test.go
metcdv3/coordinator.go

This commit adds the ability to pass in a function to the fairbalancer
for etcdv3 metafora balancer that will filter out nodes you don't want
to balance across. This will allow us to isolate balancing to canary and
non-canary deployments of metafora.
This commit also updates the package path for etcd now that it has moved
gihub orgs.

Add ability to filter out nodes from the balancer queries

---

metcdv3/client.go

It can be useful to retrieve the current tasks, but this may not apply to all clients. Embedded, for instance, cannot reasonably get this information. So lets just add it for tooling and places where we may want to type assert its existence.

add metcdv3 only Tasks method

---

.travis.yml
go.mod
go.sum
statemachine/errors.go
statemachine/errors_test.go
statemachine/statemachine.go

This PR implements the error interface for `statemachine.Err`. The change preserves the existing external interface, implements the error interface, and ~~embeds `error`~~ adds a private field `baseErr` so that the type is a proper error and can be converted back to its underlying error type using `errors.As()`. A constructor is added to simplify instantiation and to allow for testing outside of the `statemachine` package, since we don't want to expose the underlying error directly.
Also updates the go directive in `go.mod` to 1.13, and requires 1.13.x in `.travis.yml` since we're now using features in the `errors` package that were introduced in 1.13

implement error interface for statemachine.Err

---

balancer_test.go
logger.go

This is a hack to switch metafora over to using gou for the short term.

fixing a logging bug in k8s

---

statemachine/statemachine.go

Changes: don't save state change when state doesn't change. 
Save spanner calls and messing with work state history.

Don't save state when it doesn't change

---

metcdv3/balancer.go

The filter was causing us to return all of the /other/ nodes, not our list of nodes. This caused the balancer to do insane things because it was using the entire irrelevant cluster list as the average

Fix inversion of filter
